import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { findEdificio } from "@/lib/ed.mongodb";

let x = findEdificio(1).catch(e => console.log(e+"error"))
/* console.log("hhhhhhhhhhhhhhhhhh",x.json()) */
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
/*  */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
